project_id = "hxxvkxapdqoucvacbzag"

[functions.demotivate]
verify_jwt = false

[functions.generate-excuses]
verify_jwt = false

[functions.generate-quote]
verify_jwt = false

[functions.generate-pet]
verify_jwt = false

[functions.time-machine]
verify_jwt = false
